name: lint
on:
  push:
    paths:
      - src/**
jobs:
  ruff:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
